"""initial schema

Revision ID: a6a61ec0d65b
Revises: 
Create Date: 2026-06-18 23:24:58.391367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a61ec0d65b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_jobs_status'), ['status'], unique=False)

    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letters_job_id'), ['job_id'], unique=False)

    op.create_table('drift_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('max_severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_reports_generated_at'), ['generated_at'], unique=False)

    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('training_dataset', sa.String(length=256), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_registry_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_registry_name'), ['name'], unique=False)

    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('top_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_logs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('prediction_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_logs_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_risk_level'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_model_version'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_decision'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_customer_id'))

    op.drop_table('prediction_logs')
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_registry_name'))
        batch_op.drop_index(batch_op.f('ix_model_registry_is_active'))

    op.drop_table('model_registry')
    with op.batch_alter_table('drift_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_reports_generated_at'))

    op.drop_table('drift_reports')
    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letters_job_id'))

    op.drop_table('dead_letters')
    with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_jobs_status'))

    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
